version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
    - "5438:5432" # using a different default port as I have a postgress db natively running on that port.
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
